### ISSUE TITLE
from_onnx assert engine is not None, 'Failed to create TensorRT engine'

### ISSUE THREAD

**Issue by dpakprajul** [open-mmlab/mmdeploy#1350]
### Checklist

- [X] I have searched related issues but cannot get the expected help.
- [ ] 2. I have read the [FAQ documentation](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/faq.md) but cannot get the expected help.
- [ ] 3. The bug has not been fixed in the latest version.

### Describe the bug

I have created detection/detection_tensorrt-fp16_dynamic-320x320-1344x1344.py but added backend_config=dict(common_config=dict(max_workspace_size=2<<30)) to solve the memory allocation error.

I have used mask_rcnn_swin-s-p4-w7_fpn_ms-crop-3x_coco_copy.py config by changing base as:
_base_ = './mask_rcnn_swin-t-p4-w7_fpn_ms-crop-3x_coco.py' by removing fp16 from original config.

But got an error:
[11/10/2022-15:02:13] [TRT] [W] -------------- The current device memory allocations dump as below --------------
[11/10/2022-15:02:13] [TRT] [W] [0]:4294967296 :HybridGlobWriter in reserveMemory: at optimizer/common/globWriter.cpp: 438 id                           x: 207 time: 0.0213889
[11/10/2022-15:02:13] [TRT] [W] [0x602000000]:1518338048 :HybridGlobWriter in reserveMemory: at optimizer/common/globWriter.c                           pp: 416 idx: 16 time: 0.000611118
[11/10/2022-15:02:13] [TRT] [W] Requested amount of GPU memory (4294967296 bytes) could not be allocated. There may not be en                           ough free memory for allocation to succeed.
[11/10/2022-15:02:13] [TRT] [W] Skipping tactic 1 due to insufficient memory on requested size of 4294967296 detected for tac                           tic 0x00000000000003ea.
[11/10/2022-15:02:13] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::144] Error Code 2: OutOfMemory (no further infor                           mation)
[11/10/2022-15:02:13] [TRT] [E] 2: [virtualMemoryBuffer.cpp::resizePhysical::144] Error Code 2: OutOfMemory (no further infor                           mation)
[11/10/2022-15:02:13] [TRT] [W] -------------- The current system memory allocations dump as below --------------
[11/10/2022-15:02:13] [TRT] [W] [0x561e4751e050]:1604 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/weigh                           tsPtr.cpp: 102 idx: 163 time: 1.36e-06
[11/10/2022-15:02:13] [TRT] [W] [0x561e51bb4320]:1642496 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/we                           ightsPtr.cpp: 102 idx: 162 time: 1.0005e-05
[11/10/2022-15:02:13] [TRT] [W] [0x561e4800bc40]:60 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/weights                           Ptr.cpp: 102 idx: 161 time: 1.18e-07
[11/10/2022-15:02:13] [TRT] [W] [0x561e475499a0]:15360 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/weig                           htsPtr.cpp: 102 idx: 160 time: 8.7e-07
[11/10/2022-15:02:13] [TRT] [W] [0x561e46dc92a0]:15360 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/weig                           htsPtr.cpp: 102 idx: 158 time: 6.93e-07
[11/10/2022-15:02:13] [TRT] [W] [0x561e4805bdf0]:60 :Cudnn Builder weights ptr in internalAllocate: at runtime/common/weights                           Ptr.cpp: 102 idx: 157 time: 2.4e-07

Further error:
[11/10/2022-15:02:13] [TRT] [W] -------------- The current device memory allocations dump as below --------------
[11/10/2022-15:02:13] [TRT] [W] [0]:4294967296 :HybridGlobWriter in reserveMemory: at optimizer/common/globWriter.cpp: 438 id                           x: 208 time: 0.0210295
[11/10/2022-15:02:13] [TRT] [W] [0x602000000]:1518338048 :HybridGlobWriter in reserveMemory: at optimizer/common/globWriter.c                           pp: 416 idx: 16 time: 0.000611118
[11/10/2022-15:02:13] [TRT] [W] Requested amount of GPU memory (4294967296 bytes) could not be allocated. There may not be en                           ough free memory for allocation to succeed.
[11/10/2022-15:02:13] [TRT] [W] Skipping tactic 2 due to insufficient memory on requested size of 4294967296 detected for tac                           tic 0x0000000000000000.
[11/10/2022-15:09:54] [TRT] [E] 1: [convolutionRunner.cpp::executeConv::465] Error Code 1: Cudnn (CUDNN_STATUS_EXECUTION_FAIL                           ED)
Process Process-3:
Traceback (most recent call last):
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/apis/core/pipeline_manager.py", line 107,                            in __call__
    ret = func(*args, **kwargs)
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/onnx2tensorrt.py", line                            79, in onnx2tensorrt
    from_onnx(
  File "/home/dee08770/anaconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdeploy/backend/tensorrt/utils.py", line 215, in                            from_onnx
    assert engine is not None, 'Failed to create TensorRT engine'
AssertionError: Failed to create TensorRT engine
2022-11-10 15:09:55,559 - mmdeploy - ERROR - `mmdeploy.backend.tensorrt.onnx2tensorrt.onnx2tensorrt` with Call id: 1 failed.                            exit.

### Reproduction

python ~/mmdeploy/tools/deploy.py    ~/mmdeploy/configs/mmdet/detection/detection_tensorrt-fp16_dynamic-320x320-1344x1344_new.py    configs/swin/mask_rcnn_swin-s-p4-w7_fpn_ms-crop-3x_coco_copy.py    ~/checkpoints/mask_rcnn_swin-s-p4-w7_fpn_fp16_ms-crop-3x_coco_20210903_104808-b92c91f1.pth    demo/demo.jpg     --work-dir ~/mmdeploy_model/mask_rcnn_swin-s-p4-w7_fpn_ms-crop-3x_coco_copy_try1     --device cuda     --dump-info

### Environment

```Shell
2022-11-10 15:32:00,086 - mmdeploy - INFO -

2022-11-10 15:32:00,086 - mmdeploy - INFO - **********Environmental information**********
2022-11-10 15:32:01,133 - mmdeploy - INFO - sys.platform: linux
2022-11-10 15:32:01,133 - mmdeploy - INFO - Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.                                       5.0]
2022-11-10 15:32:01,133 - mmdeploy - INFO - CUDA available: True
2022-11-10 15:32:01,133 - mmdeploy - INFO - GPU 0: Tesla P100-PCIE-16GB
2022-11-10 15:32:01,133 - mmdeploy - INFO - GPU 1,2,3: NVIDIA TITAN X (Pascal)
2022-11-10 15:32:01,133 - mmdeploy - INFO - CUDA_HOME: /home/dee08770/anaconda3/envs/mmdeploy
2022-11-10 15:32:01,133 - mmdeploy - INFO - NVCC: Cuda compilation tools, release 11.3, V11.3.122
2022-11-10 15:32:01,133 - mmdeploy - INFO - GCC: gcc (Debian 10.2.1-6) 10.2.1 20210110
2022-11-10 15:32:01,133 - mmdeploy - INFO - PyTorch: 1.12.1
2022-11-10 15:32:01,134 - mmdeploy - INFO - PyTorch compiling details: PyTorch built with:
  - GCC 9.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904 for Intel(R) 64 archi                                       tecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_5                                       0;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,                                       code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=co                                       mpute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.3.2  (built against CUDA 11.5)
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.3.2, CXX_                                       COMPILER=/opt/rh/devtoolset-9/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisib                                       ility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -D                                       USE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2                                        -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-li                                       mits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-                                       result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-d                                       eclarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-e                                       rror=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-mayb                                       e-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-s                                       tringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VER                                       SION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=                                       ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF,

2022-11-10 15:32:01,134 - mmdeploy - INFO - TorchVision: 0.13.1
2022-11-10 15:32:01,134 - mmdeploy - INFO - OpenCV: 4.6.0
2022-11-10 15:32:01,134 - mmdeploy - INFO - MMCV: 1.6.2
2022-11-10 15:32:01,134 - mmdeploy - INFO - MMCV Compiler: GCC 9.3
2022-11-10 15:32:01,134 - mmdeploy - INFO - MMCV CUDA Compiler: 11.3
2022-11-10 15:32:01,134 - mmdeploy - INFO - MMDeploy: 0.9.0+917643f
2022-11-10 15:32:01,134 - mmdeploy - INFO -

2022-11-10 15:32:01,134 - mmdeploy - INFO - **********Backend information**********
2022-11-10 15:32:01,911 - mmdeploy - INFO - onnxruntime: None   ops_is_avaliable : False
2022-11-10 15:32:01,960 - mmdeploy - INFO - tensorrt: 8.4.1.5   ops_is_avaliable : True
2022-11-10 15:32:02,073 - mmdeploy - INFO - ncnn: None  ops_is_avaliable : False
2022-11-10 15:32:02,095 - mmdeploy - INFO - pplnn_is_avaliable: False
2022-11-10 15:32:02,160 - mmdeploy - INFO - openvino_is_avaliable: False
2022-11-10 15:32:02,244 - mmdeploy - INFO - snpe_is_available: False
2022-11-10 15:32:02,286 - mmdeploy - INFO - ascend_is_available: False
2022-11-10 15:32:02,322 - mmdeploy - INFO - coreml_is_available: False
2022-11-10 15:32:02,323 - mmdeploy - INFO -

2022-11-10 15:32:02,323 - mmdeploy - INFO - **********Codebase information**********
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmdet:      2.25.2
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmseg:      None
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmcls:      None
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmocr:      None
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmedit:     None
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmdet3d:    None
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmpose:     None
2022-11-10 15:32:02,327 - mmdeploy - INFO - mmrotate:   None
```

**Comment by hanrui1sensetime** [comment]
mask rcnn should use deploy configs which is in `mmdeploy/configs/mmdet/instance-seg`, not in `~/mmdeploy/configs/mmdet/detection` folder.

**Comment by dpakprajul** [comment]
> 

Sorry I forgot to mention that I changed the maskrcnn to FasterRCNN in the config.
    '../_base_/models/faster_rcnn_r50_fpn.py',
    '../_base_/datasets/coco_instance.py',
    '../_base_/schedules/schedule_1x.py', '../_base_/default_runtime.py'
]

pretrained = 'https://github.com/SwinTransformer/storage/releases/download/v1.0.0/swin_tiny_patch4_window7_224.pth'  # noqa

model = dict(
    type='FasterRCNN',
    backbone=dict(
        _delete_=True,
        type='SwinTransformer',
        embed_dims=96,
        depths=[2, 2, 6, 2],
        num_heads=[3, 6, 12, 24],
        window_size=7,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.,
        attn_drop_rate=0.,
        drop_path_rate=0.2,
        patch_norm=True,
        out_indices=(0, 1, 2, 3),
        with_cp=False,
        convert_weights=True,
        init_cfg=dict(type='Pretrained', checkpoint=pretrained)),
    neck=dict(in_channels=[96, 192, 384, 768]))

I faced the similar problem before and used instance-seg instead. But I wanted detection rather than segmentation and used FasterRCNN in the config and works fine.

**Comment by dpakprajul** [comment]
The issue is solved now. The problem was low allocation of memory (GPU).
