### ISSUE TITLE
The problem of cuda illegal memory access encountered by multi-threaded model inference.

### ISSUE THREAD

**Issue by duqi007** [open-mmlab/mmdeploy#591]
Hello, developer, when I converted the model to tensorRT and conducted inference in multiple threads at the same time, I encountered an error of cuda accessing memory. Could you please tell me how to solve this problem, except for locking. Without model conversion, the multi-threaded model inference did not encounter the error of cuda access. Can you explain the reason for this? Below is a list of the errors I encountered and the environment I was using. Thanks.
`cuda: 11.2
cudnn: 8.2.1.32
tensorrt: 8.2.3.0
torch: 1.10.0+cu111
python: 3.8
`
The inference used is the officially given api, but when I implemented my service, I extracted the implementation in the inference_model, encapsulated it with a class, loaded the model in __init__, and called the inference directly.
```
from mmdeploy.utils import get_input_shape, load_config 
from mmdeploy.apis.utils import build_task_processor

def __init__(self, config_path):
        config = load_configs(config_path)
        self.device = 'cuda:'+str(config['device'])
        self.contour_config = config['contour_config']
        self.weight = config['weight']
        self.deploy_config = config['deploy_config']
        self.palette = self.get_palette(10)
        deploy_cfg, model_cfg = load_config(self.deploy_config, self.contour_config)
        self.task_processor = build_task_processor(model_cfg, deploy_cfg, self.device)
        self.model = self.task_processor.init_backend_model([self.weight])
        self.input_shape = get_input_shape(deploy_cfg)

def get_segmentation(self, img):
        model_inputs, _ = self.task_processor.create_input(img, self.input_shape)
        with torch.no_grad():
            result = self.task_processor.run_inference(self.model, model_inputs)
        result = result[0]
        result = PILImage.fromarray(np.asarray(result, dtype=np.uint8))
        result.putpalette(self.palette)
        result = result.convert("RGB")
        result = cv2.cvtColor(np.asarray(result),cv2.COLOR_RGB2BGR)
        return result
```
Here is the configuration:
```
{
    "weight": "/DATACENTER3/qi.du/seg_deploys/end2end.engine",
    "device": 0,
    "contour_config" : "/DATACENTER3/qi.du/maliang/back_end/config/contour_detection/upernet_convnext_base_fp16_640x640_160k_ade20k.py",
    "deploy_config" : "/DATACENTER3/qi.du/maliang/back_end/config/contour_detection/segmentation_tensorrt_static-512x1024.py"
}
```
Below is the error print:
```
[ERROR  ] _server:_call_behavior:453 - Exception calling application: CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/DATACENTER3/qi.du/maliang/back_end/contour_detection/../contour_detection/service/service.py", line 218, in detect
    seg_result = self.contour_detect.get_segmentation(img=img)
  File "/DATACENTER3/qi.du/maliang/back_end/contour_detection/../contour_detection/src/parsing_detect.py", line 61, in get_segmentation
    result = self.task_processor.run_inference(self.model, model_inputs)
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 183, in run_inference
    return model(**model_inputs, return_loss=False, rescale=True)
  File "/home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 82, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs)
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 109, in forward_test
    outputs = [out.detach().cpu().numpy() for out in outputs]
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 109, in <listcomp>
    outputs = [out.detach().cpu().numpy() for out in outputs]
RuntimeError: CUDA error: an illegal memory access was encountered
2022-06-12 10:30:34,174-ERROR-grpc._server::_server|453:: Exception calling application: CUDA error: an illegal memory access was encountered
Traceback (most recent call last):
  File "/home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/grpc/_server.py", line 443, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/DATACENTER3/qi.du/maliang/back_end/contour_detection/../contour_detection/service/service.py", line 218, in detect
    seg_result = self.contour_detect.get_segmentation(img=img)
  File "/DATACENTER3/qi.du/maliang/back_end/contour_detection/../contour_detection/src/parsing_detect.py", line 61, in get_segmentation
    result = self.task_processor.run_inference(self.model, model_inputs)
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation.py", line 183, in run_inference
    return model(**model_inputs, return_loss=False, rescale=True)
  File "/home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 82, in forward
    outputs = self.forward_test(input_img, img_metas, *args, **kwargs)
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 109, in forward_test
    outputs = [out.detach().cpu().numpy() for out in outputs]
  File "/DATACENTER3/qi.du/mmdeploy/mmdeploy/codebase/mmseg/deploy/segmentation_model.py", line 109, in <listcomp>
    outputs = [out.detach().cpu().numpy() for out in outputs]
RuntimeError: CUDA error: an illegal memory access was encountered
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: an illegal memory access was encountered
Exception raised from create_event_internal at /pytorch/c10/cuda/CUDACachingAllocator.cpp:733 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f3a3844f2f2 in /home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x5b (0x7f3a3844c67b in /home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x809 (0x7f3a3e72d1f9 in /home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x54 (0x7f3a384373a4 in /home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x6e473a (0x7f39ddf7673a in /home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x6e47d1 (0x7f39ddf767d1 in /home/qi.du/miniconda3/envs/maliang/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #34: <unknown function> + 0x8609 (0x7f3a50893609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #35: clone + 0x43 (0x7f3a507b8133 in /lib/x86_64-linux-gnu/libc.so.6)
```
The above implementation has no errors in single inference , but the above errors occur in multi-threaded inference . I hope you can help me explain the reason, and it would be better if you can propose a solution. grateful

**Comment by grimoire** [comment]
Hi, did you share the TensorRT context between different threads?
TensorRT recommends the user create different contexts in each thread. You can modify [TRTWrapper](https://github.com/open-mmlab/mmdeploy/blob/e84bc30f4a036dd19cb3af854203922a91098e84/mmdeploy/backend/tensorrt/wrapper.py?_pjax=%23js-repo-pjax-container%2C+.context-loader-container%2C+%5Bdata-pjax-container%5D#L91) to create context at the begin of each thread.
And are you using different GPU on different threads? The engine will bind to the conversion device, If you want to use it on non-default device, please convert it again with the device id you want.

**Comment by duqi007** [comment]
> Hi, did you share the TensorRT context between different threads? TensorRT recommends the user create different contexts in each thread. You can modify [TRTWrapper](https://github.com/open-mmlab/mmdeploy/blob/e84bc30f4a036dd19cb3af854203922a91098e84/mmdeploy/backend/tensorrt/wrapper.py?_pjax=%23js-repo-pjax-container%2C+.context-loader-container%2C+%5Bdata-pjax-container%5D#L91) to create context at the begin of each thread. And are you using different GPU on different threads? The engine will bind to the conversion device, If you want to use it on non-default device, please convert it again with the device id you want.

Thank you very much for your answer. I modified the TRTWrapper and then ran it, which can indeed solve the problem I am encountering now, but each thread creates a context, and the changes of memory during the running of the program will be great, and the creation and destruction of the context also brings a lot of consumption. It is too time-consuming as a service, and the inference_model API will load the model and then perform inference every time it is called. The time to load the model is much greater than the time used for inference, so it is not suitable for for a service, my final solution is to choose locking to solve this problem, thanks again.

**Comment by grimoire** [comment]
inference_model is designed to test the converted model. Please try our SDK, which provide faster inference API.

**Comment by duqi007** [comment]
> inference_model is designed to test the converted model. Please try our SDK, which provide faster inference API.

Thanks, I tried to use your SDK (python), but found that the inference speed is not as fast as you said, and the inference speed of `result = task_processor.run_inference(model, model_inputs)` is the same. Thank you very much for your help, I have solved the problem, THKU.

**Comment by songsonggithub** [comment]
> 

how to solve this problem? can you teach me by key code? thanks

**Comment by duqi007** [comment]
> > 
> 
> how to solve this problem? can you teach me by key code? thanks
As discussed earlier, a TensorRT Context needs to be created for each thread to ensure data security between different threads. One solution is to create a context for each thread, which will allocate a lot of memory. Another solution is to use locks. It is guaranteed that only one thread is accessed at a time. As for the code implementation, it is actually very simple. You can split the internal implementation of the inference_model function. However, it is recommended to use the developer's suggestion to use SDK inference , which will be better to use locks.

**Comment by songsonggithub** [comment]
thanks for you reply, though I have split inference_model, but I still how to merge threading with it, maybe the key code is more important, and it is very helpful for me.&nbsp;






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 晚上8:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdeploy] The problem of cuda illegal memory access encountered by multi-threaded model inference. (Issue #591)





    
how to solve this problem? can you teach me by key code? thanks
 As discussed earlier, a TensorRT Context needs to be created for each thread to ensure data security between different threads. One solution is to create a context for each thread, which will allocate a lot of memory. Another solution is to use locks. It is guaranteed that only one thread is accessed at a time. As for the code implementation, it is actually very simple. You can split the internal implementation of the inference_model function. However, it is recommended to use the developer's suggestion to use SDK inference , which will be better to use locks.

**Comment by duqi007** [comment]
One way: lock
You can lock in the following way, taking keypoint detection as an example.
``` python
class PoseDetectionWrapper():
    def __init__(self, config_path=''):
        """
        read config
        """
        config = load_configs(config_path)
        self.device = 'cuda:'+str(config['device'])
        self.pose_config = config['pose_config']
        self.weight = config['weight']
        self.deploy_config = config['deploy_config']
        deploy_cfg, model_cfg = load_config(self.deploy_config, self.pose_config)
        self.task_processor = build_task_processor(model_cfg, deploy_cfg, self.device)
        self.model = self.task_processor.init_backend_model([self.weight])
        self.input_shape = get_input_shape(deploy_cfg)
        self.detector_lck = Lock()

    def get_pose_result(self, img):
        model_inputs, _ = self.task_processor.create_input(img, self.input_shape)
        # do like this
        self.detector_lck.acquire()
        with torch.no_grad():
            infer_result = self.task_processor.run_inference(self.model, model_inputs)
        self.detector_lck.release()
        result = {}
        result["keypoints"] = np.squeeze(infer_result[0]["preds"], axis=0)
        result["bbox"] = infer_result[0]["boxes"]
        return [result]
```
SDK inference method is the same.
The second method: modify the mmdeloy file [TRTWrapper](https://github.com/open-mmlab/mmdeploy/blob/e84bc30f4a036dd19cb3af854203922a91098e84/mmdeploy/backend/tensorrt/wrapper.py?_pjax=%23js-repo-pjax-container%2C+.context-loader-container%2C+%5Bdata-pjax-container%5D#L91) Instead of creating the context in __init__, create the context where the context is used in the forward function. Then compile the source code to install. It is not recommended to use this。
In fact, I don't know enough about it, but it has solved my problem. This is just my small suggestion.

**Comment by songsonggithub** [comment]
> One way: lock You can lock in the following way, taking keypoint detection as an example.
> 
> ```python
> class PoseDetectionWrapper():
>     def __init__(self, config_path=''):
>         """
>         read config
>         """
>         config = load_configs(config_path)
>         self.device = 'cuda:'+str(config['device'])
>         self.pose_config = config['pose_config']
>         self.weight = config['weight']
>         self.deploy_config = config['deploy_config']
>         deploy_cfg, model_cfg = load_config(self.deploy_config, self.pose_config)
>         self.task_processor = build_task_processor(model_cfg, deploy_cfg, self.device)
>         self.model = self.task_processor.init_backend_model([self.weight])
>         self.input_shape = get_input_shape(deploy_cfg)
>         self.detector_lck = Lock()
> 
>     def get_pose_result(self, img):
>         model_inputs, _ = self.task_processor.create_input(img, self.input_shape)
>         # do like this
>         self.detector_lck.acquire()
>         with torch.no_grad():
>             infer_result = self.task_processor.run_inference(self.model, model_inputs)
>         self.detector_lck.release()
>         result = {}
>         result["keypoints"] = np.squeeze(infer_result[0]["preds"], axis=0)
>         result["bbox"] = infer_result[0]["boxes"]
>         return [result]
> ```
> 
> SDK inference method is the same. The second method: modify the mmdeloy file [TRTWrapper](https://github.com/open-mmlab/mmdeploy/blob/e84bc30f4a036dd19cb3af854203922a91098e84/mmdeploy/backend/tensorrt/wrapper.py?_pjax=%23js-repo-pjax-container%2C+.context-loader-container%2C+%5Bdata-pjax-container%5D#L91) Instead of creating the context in **init**, create the context where the context is used in the forward function. Then compile the source code to install. It is not recommended to use this。 In fact, I don't know enough about it, but it has solved my problem. This is just my small suggestion.

it works, thanks very much, good luck.

**Comment by songsonggithub** [comment]
ok, now I try as your way, thanks really.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "open-mmlab/mmdeploy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月20日(星期一) 晚上9:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [open-mmlab/mmdeploy] The problem of cuda illegal memory access encountered by multi-threaded model inference. (Issue #591)





 
One way: lock
 You can lock in the following way, taking keypoint detection as an example.
 class PoseDetectionWrapper():     def __init__(self, config_path=''):         """         read config         """         config = load_configs(config_path)         self.device = 'cuda:'+str(config['device'])         self.pose_config = config['pose_config']         self.weight = config['weight']         self.deploy_config = config['deploy_config']         deploy_cfg, model_cfg = load_config(self.deploy_config, self.pose_config)         self.task_processor = build_task_processor(model_cfg, deploy_cfg, self.device)         self.model = self.task_processor.init_backend_model([self.weight])         self.input_shape = get_input_shape(deploy_cfg)         self.detector_lck = Lock()     def get_pose_result(self, img):         model_inputs, _ = self.task_processor.create_input(img, self.input_shape)         # do like this         self.detector_lck.acquire()         with torch.no_grad():             infer_result = self.task_processor.run_inference(self.model, model_inputs)         self.detector_lck.release()         result = {}         result["keypoints"] = np.squeeze(infer_result[0]["preds"], axis=0)         result["bbox"] = infer_result[0]["boxes"]         return [result]
 
SDK inference method is the same.
 The second method: modify the mmdeloy file TRTWrapper Instead of creating the context in init, create the context where the context is used in the forward function. Then compile the source code to install. It is not recommended to use this。
 In fact, I don't know enough about it, but it has solved my problem. This is just my small suggestion.
