### ISSUE TITLE
ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by lijoe123** [open-mmlab/mmdeploy#913]
I follow the [get_started.md](https://github.com/open-mmlab/mmdeploy/blob/master/docs/en/get_started.md) to convert model with Linux-x86_64, CUDA 11.x, TensorRT 8.2.5.1, just like the `md` show 
![image](https://user-images.githubusercontent.com/86214036/185114595-4e5425ec-e2b8-4ac9-a97f-23190957b995.png)

I got the problem ：**ImportError: libnvinfer.so.8: cannot open shared object file: No such file or directory**
I had run the
![image](https://user-images.githubusercontent.com/86214036/185113917-890610ce-eaa2-4587-8346-101238c95ba2.png)

but still had the problem!!!!! My env as follow
![image](https://user-images.githubusercontent.com/86214036/185114813-f0e4d0b9-c658-4929-b982-ac7c431cd306.png)
![image](https://user-images.githubusercontent.com/86214036/185114845-0c225f10-d1b3-4d6e-90a8-0bb1d69b7bd8.png)

Could you please tell me how to fix this problem?Thank you!

**Comment by tpoisonooo** [comment]
@lvhan028

**Comment by lvhan028** [comment]
It seems you've installed tensorrt 8.2.5.1 whl file. But you set TensorRT 8.4.1.5 libraries to env `LD_LIBRARY_PATH`

**Comment by lijoe123** [comment]
thank you for your answer! Actually,the img above is an example, I had run these codes,
![3047C83E01FD9FC087CC752BCAC87F4A](https://user-images.githubusercontent.com/86214036/185289237-e05de646-d00f-42f8-9b0c-65320826bec4.jpg)
And the `bashrc` file can't find the tensorrt
![3B2ED70D28225F81974137B9DC9CBD9F](https://user-images.githubusercontent.com/86214036/185291147-f5e6d392-d322-4833-91a5-c75e062ce429.jpg)
![82D7AB68EDEABA87086E2E5F51929D5D](https://user-images.githubusercontent.com/86214036/185291154-2d971b11-c5a6-44cc-88a1-f8e134adc230.jpg)

**Comment by lvhan028** [comment]
`export` command only takes effect in the current shell. If you want to set the environment variables permanently for all shell sessions, please add them to `~/.bashrc` file.

**Comment by fuxuelinwudi** [comment]
thanks, i add tensorrt install path into my envs variance, and then it works.
